const fs = require('fs');

const translations = {
    en: {
        "order_shipping_details": "Shipping Details",
        "order_field_email": "Email address",
        "order_field_name": "Full name",
        "order_field_address1": "Address line 1",
        "order_field_address2": "Address line 2 (optional)",
        "order_field_city": "City",
        "order_field_postal": "Postal code",
        "order_field_country": "Select country",
        "order_field_phone": "Phone (optional)",
        "order_error_email": "Please enter a valid email address",
        "order_error_name": "Please enter your full name",
        "order_error_address": "Please enter your address",
        "order_error_city": "Please enter your city",
        "order_error_postal": "Please enter your postal code",
        "order_error_country": "Please select your country"
    },
    it: {
        "order_shipping_details": "Dati di Spedizione",
        "order_field_email": "Indirizzo email",
        "order_field_name": "Nome e cognome",
        "order_field_address1": "Indirizzo (via, numero)",
        "order_field_address2": "Indirizzo riga 2 (opzionale)",
        "order_field_city": "Città",
        "order_field_postal": "CAP",
        "order_field_country": "Seleziona paese",
        "order_field_phone": "Telefono (opzionale)",
        "order_error_email": "Inserisci un indirizzo email valido",
        "order_error_name": "Inserisci il tuo nome e cognome",
        "order_error_address": "Inserisci il tuo indirizzo",
        "order_error_city": "Inserisci la tua città",
        "order_error_postal": "Inserisci il tuo CAP",
        "order_error_country": "Seleziona il tuo paese"
    },
    de: {
        "order_shipping_details": "Lieferdetails",
        "order_field_email": "E-Mail-Adresse",
        "order_field_name": "Vollständiger Name",
        "order_field_address1": "Adresszeile 1",
        "order_field_address2": "Adresszeile 2 (optional)",
        "order_field_city": "Stadt",
        "order_field_postal": "PLZ",
        "order_field_country": "Land auswählen",
        "order_field_phone": "Telefon (optional)",
        "order_error_email": "Bitte geben Sie eine gültige E-Mail-Adresse ein",
        "order_error_name": "Bitte geben Sie Ihren vollständigen Namen ein",
        "order_error_address": "Bitte geben Sie Ihre Adresse ein",
        "order_error_city": "Bitte geben Sie Ihre Stadt ein",
        "order_error_postal": "Bitte geben Sie Ihre PLZ ein",
        "order_error_country": "Bitte wählen Sie Ihr Land"
    },
    es: {
        "order_shipping_details": "Datos de Envío",
        "order_field_email": "Correo electrónico",
        "order_field_name": "Nombre completo",
        "order_field_address1": "Dirección línea 1",
        "order_field_address2": "Dirección línea 2 (opcional)",
        "order_field_city": "Ciudad",
        "order_field_postal": "Código postal",
        "order_field_country": "Seleccionar país",
        "order_field_phone": "Teléfono (opcional)",
        "order_error_email": "Introduce un correo electrónico válido",
        "order_error_name": "Introduce tu nombre completo",
        "order_error_address": "Introduce tu dirección",
        "order_error_city": "Introduce tu ciudad",
        "order_error_postal": "Introduce tu código postal",
        "order_error_country": "Selecciona tu país"
    },
    fr: {
        "order_shipping_details": "Détails de Livraison",
        "order_field_email": "Adresse e-mail",
        "order_field_name": "Nom complet",
        "order_field_address1": "Adresse ligne 1",
        "order_field_address2": "Adresse ligne 2 (optionnel)",
        "order_field_city": "Ville",
        "order_field_postal": "Code postal",
        "order_field_country": "Sélectionner le pays",
        "order_field_phone": "Téléphone (optionnel)",
        "order_error_email": "Veuillez entrer une adresse e-mail valide",
        "order_error_name": "Veuillez entrer votre nom complet",
        "order_error_address": "Veuillez entrer votre adresse",
        "order_error_city": "Veuillez entrer votre ville",
        "order_error_postal": "Veuillez entrer votre code postal",
        "order_error_country": "Veuillez sélectionner votre pays"
    },
    pl: {
        "order_shipping_details": "Dane Wysyłki",
        "order_field_email": "Adres e-mail",
        "order_field_name": "Imię i nazwisko",
        "order_field_address1": "Adres linia 1",
        "order_field_address2": "Adres linia 2 (opcjonalnie)",
        "order_field_city": "Miasto",
        "order_field_postal": "Kod pocztowy",
        "order_field_country": "Wybierz kraj",
        "order_field_phone": "Telefon (opcjonalnie)",
        "order_error_email": "Podaj prawidłowy adres e-mail",
        "order_error_name": "Podaj swoje imię i nazwisko",
        "order_error_address": "Podaj swój adres",
        "order_error_city": "Podaj swoje miasto",
        "order_error_postal": "Podaj swój kod pocztowy",
        "order_error_country": "Wybierz swój kraj"
    },
    pt: {
        "order_shipping_details": "Detalhes de Envio",
        "order_field_email": "Endereço de e-mail",
        "order_field_name": "Nome completo",
        "order_field_address1": "Endereço linha 1",
        "order_field_address2": "Endereço linha 2 (opcional)",
        "order_field_city": "Cidade",
        "order_field_postal": "Código postal",
        "order_field_country": "Selecionar país",
        "order_field_phone": "Telefone (opcional)",
        "order_error_email": "Insira um endereço de e-mail válido",
        "order_error_name": "Insira o seu nome completo",
        "order_error_address": "Insira o seu endereço",
        "order_error_city": "Insira a sua cidade",
        "order_error_postal": "Insira o seu código postal",
        "order_error_country": "Selecione o seu país"
    },
    ru: {
        "order_shipping_details": "Данные Доставки",
        "order_field_email": "Электронная почта",
        "order_field_name": "ФИО",
        "order_field_address1": "Адрес строка 1",
        "order_field_address2": "Адрес строка 2 (необязательно)",
        "order_field_city": "Город",
        "order_field_postal": "Почтовый индекс",
        "order_field_country": "Выберите страну",
        "order_field_phone": "Телефон (необязательно)",
        "order_error_email": "Введите действительный адрес электронной почты",
        "order_error_name": "Введите ваше полное имя",
        "order_error_address": "Введите ваш адрес",
        "order_error_city": "Введите ваш город",
        "order_error_postal": "Введите ваш почтовый индекс",
        "order_error_country": "Выберите вашу страну"
    },
    uk: {
        "order_shipping_details": "Дані Доставки",
        "order_field_email": "Електронна пошта",
        "order_field_name": "Повне ім'я",
        "order_field_address1": "Адреса рядок 1",
        "order_field_address2": "Адреса рядок 2 (необов'язково)",
        "order_field_city": "Місто",
        "order_field_postal": "Поштовий індекс",
        "order_field_country": "Оберіть країну",
        "order_field_phone": "Телефон (необов'язково)",
        "order_error_email": "Введіть дійсну адресу електронної пошти",
        "order_error_name": "Введіть ваше повне ім'я",
        "order_error_address": "Введіть вашу адресу",
        "order_error_city": "Введіть ваше місто",
        "order_error_postal": "Введіть ваш поштовий індекс",
        "order_error_country": "Оберіть вашу країну"
    }
};

for (const [lang, strings] of Object.entries(translations)) {
    const filePath = './messages/' + lang + '.json';
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    Object.assign(data.Index, strings);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 4) + '\n');
    console.log('OK ' + lang + ' — ' + Object.keys(strings).length + ' keys');
}
